name: Deploy to vast.ai

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install vastai
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.gpu -t althen-rag-gpu:latest .
    
    - name: Push to Docker Registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag althen-rag-gpu:latest $DOCKER_USERNAME/althen-rag-gpu:latest
        docker push $DOCKER_USERNAME/althen-rag-gpu:latest
    
    - name: Deploy to vast.ai
      env:
        VAST_API_KEY: ${{ secrets.VAST_API_KEY }}
      run: |
        # This is a placeholder for vast.ai deployment
        # You would need to implement the actual deployment logic
        echo "Deployment to vast.ai would happen here"
        # Example: vastai create instance --image $DOCKER_USERNAME/althen-rag-gpu:latest ...